site_name: SysEleven Stack Documentation
theme_dir: /usr/share/mkdocs/themes/mkdocs_bootswatch/flatly/
google_analytics: ['UA-4634575-5', 'doc.syselevenstack.com']
repo_name: "GitHub"
repo_url: "https://github.com/syseleven/syselevenstack-documentation"

pages:
  - index.md
  - 'Tutorials': 
    - 'Erste Schritte': 'tutorials/01-firststeps.md'
    - 'API-Zugriff': 'tutorials/02-kickstart.md'
    - 'Server in Gruppen organisieren': 'tutorials/03-servergruppen.md'
    - 'Minimale CoreOS Umgebung': 'tutorials/04-coreos.md'
    - 'Stack-Ressourcen logisch aufeinander aufbauen': 'tutorials/05-dependencies.md'
  - 'Dokumentation':
    - 'Compute': 'documentation/compute.md'
    - 'Networking': 'documentation/networking.md'
    - 'Block Storage': 'documentation/block-storage.md'
    - 'Object Storage': 'documentation/object-storage.md'
    - 'Orchestration': 'documentation/orchestration.md'

copyright: SysEleven Stack is made with â™¥ in Berlin.<br/>
    Switch to <a href="https://doc.syselevenstack.com/en/">english documentation</a>
    For further questions, don't hesitate to contact us at <a href="mailto:cloudsupport@syseleven.de">cloudsupport@syseleven.de</a>
