site_name: SysEleven Stack Documentation
theme_dir: /usr/share/mkdocs/themes/mkdocs_bootswatch/flatly/
google_analytics: ['UA-4634575-5', 'doc.syselevenstack.com']
repo_name: "GitHub"
repo_url: "https://github.com/syseleven/syselevenstack-documentation"

pages:
  - index.md
  - 'Tutorials': 
    - 'First Steps': 'tutorials/01-firststeps.md'
    - 'API Access': 'tutorials/02-kickstart.md'
    - 'Organising instances in groups': 'tutorials/03-servergruppen.md'
    - 'Minimal CoreOS setup': 'tutorials/04-coreos.md'
    - 'Built stack-ressources logically upon another': 'tutorials/05-dependencies.md'
  - 'Documentation':
    - 'Compute': 'documentation/compute.md'
    - 'Networking': 'documentation/networking.md'
    - 'Block Storage': 'documentation/block-storage.md'
    - 'Object Storage': 'documentation/object-storage.md'
    - 'Orchestration': 'documentation/orchestration.md'

copyright: SysEleven Stack is made with â™¥ in Berlin.<br/>
    Switch to <a href="https://doc.syselevenstack.com/de/">german documentation</a>
    For further questions, don't hesitate to contact us at <a href="mailto:cloudsupport@syseleven.de">cloudsupport@syseleven.de</a>
